# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_serdesri_wrappers", use_symbols = TRUE, package_name = "serdesri")

#' @docType package
#' @usage NULL
#' @useDynLib serdesri, .registration = TRUE
NULL

as_multipoint <- function(x) .Call(wrap__as_multipoint, x)

as_point <- function(x) .Call(wrap__as_point, x)

as_linestring_polyline <- function(x) .Call(wrap__as_linestring_polyline, x)

as_polyline <- function(x) .Call(wrap__as_polyline, x)

as_poly_polygon <- function(x) .Call(wrap__as_poly_polygon, x)

as_polygon <- function(x) .Call(wrap__as_polygon, x)

as_attribute <- function(x, n) invisible(.Call(wrap__as_attribute, x, n))

sfc_linestring_features_2d <- function(x) .Call(wrap__sfc_linestring_features_2d, x)

sfc_linestring_features_3d <- function(x) .Call(wrap__sfc_linestring_features_3d, x)

sfc_linestring_featureset_2d <- function(x, sr) .Call(wrap__sfc_linestring_featureset_2d, x, sr)

sfc_linestring_featureset_3d <- function(x, sr) .Call(wrap__sfc_linestring_featureset_3d, x, sr)

sfc_multilinestring_features_2d <- function(x) .Call(wrap__sfc_multilinestring_features_2d, x)

sfc_multilinestring_features_3d <- function(x) .Call(wrap__sfc_multilinestring_features_3d, x)

sfc_multilinestring_featureset_2d <- function(x, sr) .Call(wrap__sfc_multilinestring_featureset_2d, x, sr)

sfc_multilinestring_featureset_3d <- function(x, sr) .Call(wrap__sfc_multilinestring_featureset_3d, x, sr)

sfc_multipoint_features_2d <- function(x) .Call(wrap__sfc_multipoint_features_2d, x)

sfc_multipoint_features_3d <- function(x) .Call(wrap__sfc_multipoint_features_3d, x)

sfc_multipoint_featureset_2d <- function(x, sr) .Call(wrap__sfc_multipoint_featureset_2d, x, sr)

sfc_multipoint_featureset_3d <- function(x, sr) .Call(wrap__sfc_multipoint_featureset_3d, x, sr)

sfc_multipolygon_features_2d <- function(x) .Call(wrap__sfc_multipolygon_features_2d, x)

sfc_multipolygon_features_3d <- function(x) .Call(wrap__sfc_multipolygon_features_3d, x)

sfc_multipolygon_featureset_2d <- function(x, sr) .Call(wrap__sfc_multipolygon_featureset_2d, x, sr)

sfc_multipolygon_featureset_3d <- function(x, sr) .Call(wrap__sfc_multipolygon_featureset_3d, x, sr)

sfc_point_features_2d <- function(x) .Call(wrap__sfc_point_features_2d, x)

sfc_point_features_3d <- function(x) .Call(wrap__sfc_point_features_3d, x)

sfc_point_featureset_2d <- function(x, sr) .Call(wrap__sfc_point_featureset_2d, x, sr)

sfc_point_featureset_3d <- function(x, sr) .Call(wrap__sfc_point_featureset_3d, x, sr)

sfc_polygon_features_2d <- function(x) .Call(wrap__sfc_polygon_features_2d, x)

sfc_polygon_features_3d <- function(x) .Call(wrap__sfc_polygon_features_3d, x)

sfc_polygon_featureset_2d <- function(x, sr) .Call(wrap__sfc_polygon_featureset_2d, x, sr)

sfc_polygon_featureset_3d <- function(x, sr) .Call(wrap__sfc_polygon_featureset_3d, x, sr)


# nolint end
