# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_serdesri_wrappers", use_symbols = TRUE, package_name = "serdesri")

#' @docType package
#' @usage NULL
#' @useDynLib serdesri, .registration = TRUE
NULL

as_multipoint <- function(x) .Call(wrap__as_multipoint, x)

as_point <- function(x) .Call(wrap__as_point, x)

as_linestring_polyline <- function(x) .Call(wrap__as_linestring_polyline, x)

as_polyline <- function(x) .Call(wrap__as_polyline, x)

as_poly_polygon <- function(x) .Call(wrap__as_poly_polygon, x)

as_polygon <- function(x) .Call(wrap__as_polygon, x)


# nolint end
