name: Cargo Doc

on:
  push:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    name: Deploy the dev version of documents to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Docs
        run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: ""
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/serde_esri